### ISSUE TITLE
how to build or use?

### ISSUE THREAD

**Issue by mbandu** [BOJIT/PlatformIO-lwIP#1]
I am quite new to platformIO. how to I build this lib? or should I just copy files+folders and use it?

thank you so much

Bandu

**Comment by BOJIT** [comment]
Hi - the library is added to `lib_deps` like any other PlatformIO library. However one of the dependencies of `PlatformIO-lwIP` is `PlatformIO-FreeRTOS`, which may need to [be configured](https://github.com/BOJIT/PlatformIO-FreeRTOS). If you are not using FreeRTOS as your base OS, or using `lwIP` in no-OS mode, this library won't be much use for you.

An example project can be seen here: https://github.com/Open-AES67/PTP-GM

I would add a word of warning: unlike `PlatformIO-FreeRTOS`, which I would consider to be stable, this library is still kind of in the 'prototype' stage. It's in need of a refresh, and I wouldn't use it for any serious work (yet).

My suggestion would be to add `lwIP` as a submodule to a repository and then provide the `arch` folder yourself. For info on porting, I would read this page: https://lwip.fandom.com/wiki/Porting_for_an_OS

Hope this helps.

James

**Comment by mbandu** [comment]
@BOJIT thanks, really appreciate your response. I can compile now. I am planning to use freeRTOS with lwip.
